### ISSUE TITLE
[Project] Website Recommendations Checklist

### ISSUE THREAD

**Issue by cherise-IK12** [cherise-IK12/marketing-projects#2]
**Q4 Goals**
- [x]  Q4 Remove Covid-19 Updates from banner and add to resources section (QW) 
- [x]  Q4 Add resources page to banner (QW)
- [x]  Q4 Add success stories/quotes to homepage (MI)
- [ ]  Q4 Add IT & MOT Personas (MI)
  - [x] MOT and IT pages have been created but are not published. Need to create persona-specific videos to finalize
- [x]  Q4 Update stats at top of page (QW)
- [x]  Q4 Update case studies with new stories (QW/MI)
- [ ]  Q4 Add new dropdown to filter resources by district size, state, region, or department (MI)
- [x]  Q4 Every resource should link to demo form and/or services page (MI)
- [ ] Make support larger or part of main grouping (QW)

**Future goals**
- [ ]  FUTURE Replace customer with “Solutions” page (LT)
- [ ] Build out solutions by use-case and persona
- [ ] Add explicit buttons for customer personas, looks more like a header and not a link (QW)
- [ ]  FUTURE New persona videos (LT) → not able to do without significant time/resources
- [ ]  FUTURE Update graphic, with new regions or add logos (MI)
- [ ] Add stats similar to example below (or add to homepage) (MI)
- [ ] Combine with information from the features page which has more interesting information. (MI)
- [ ] The Features and Services pages are the most exciting at the moment. Add these to the Global Header (QW)
- [ ]  FUTURE Ideally, the homepage should look more like the features page (MI)
- [ ]  FUTURE Update pricing page, add comparison to per user/per month pricing of competitors (MI)
